### ISSUE TITLE
npm install failed in package/thicket-webapp

### ISSUE THREAD

**Issue by josselinchevalay** [citrusbyte/thicket#307]
hi, 

i try to install your web app but i run npm install i have this error : 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/josselin/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.16.0-parrot12-amd64
gyp ERR! command "/home/josselin/.nvm/versions/node/v10.5.0/bin/node" "/home/josselin/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/josselin/develop/thicket/packages/thicket-webapp/node_modules/leveldown
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```
any idea ?

**Comment by AquiGorka** [comment]
Hello @josselinchevalay 
Is that from `npm i` at root?
Could you let me know your node, npm/yarn versions?

**Comment by AquiGorka** [comment]
@josselinchevalay I see you are running `Debian`, is it possible you are running `node@10`?
I was able to reproduce a similar issue under those conditions.
By downgrading node to either 8 or 9 everything seems to work as it should.

By the way, this happens in `MacOS` too. I will add the proper instructions to the README.

**Comment by josselinchevalay** [comment]
yep i  use node10 . i will try with 9.

**Comment by AquiGorka** [comment]
@josselinchevalay let me know when you can install the dependencies and work with Thicket.

**Comment by josselinchevalay** [comment]
ok now (with node 9) i can npm install but when i start webapp i have this error

```./src/components/Gif/index.js
Module not found: Can't resolve 'thicket-elements/lib/ShareLink' in '/home/josselin/develop/thicket/packages/thicket-webapp/src/components/Gif'```

in index page

**Comment by AquiGorka** [comment]
After installing the dependencies did you run `yarn bootstrap`?

**Comment by josselinchevalay** [comment]
i'll test that this night

**Comment by josselinchevalay** [comment]
in root when i run yarn bootstrap i have this error

yarn bootstrap
yarn run v1.7.0
$ lerna bootstrap && lerna run prepublish
lerna info version 2.11.0
lerna info versioning independent
lerna info Bootstrapping 3 packages
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn install --mutex network:42424 --non-interactive
lerna ERR! error thicket@1.0.0: The engine "node" is incompatible with this module. Expected version ">=4.x.x <=9.x.x".
lerna ERR! error Found incompatible module
lerna ERR! [1/5] Validating package.json...
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/josselin/develop/thicket/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn install --mutex network:42424 --non-interactive
error thicket@1.0.0: The engine "node" is incompatible with this module. Expected version ">=4.x.x <=9.x.x".
error Found incompatible module
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (/home/josselin/develop/thicket/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
   '[1/5] Validating package.json...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr:
   'error thicket@1.0.0: The engine "node" is incompatible with this module. Expected version ">=4.x.x <=9.x.x".\nerror Found incompatible module\n',
  failed: true,
  signal: null,
  cmd: 'yarn install --mutex network:42424 --non-interactive',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by josselinchevalay** [comment]
ok with

node js : v8.11.2
npm : 5.6.0
yarn : 1.7.0 

seems works fine. I'll update readme about that.

**Comment by AquiGorka** [comment]
Thanks! Odd about the node version, I did test with version 9.
